apiVersion: apps/v1
kind: Deployment
metadata: 
  name: airflow 
spec: 
  replicas: 1 
  selector:
    matchLabels:
      app: airflow
  template:
    metadata: 
      labels: 
        app: airflow 
    spec: 
      containers:
        - name: airflow
          image: apache/airflow:2.9.0 
          command: ["airflow", "webserver"]
          ports:
            - containerPort: 8080 
          readinessProbe:
            httpGet:
              path: /
              port: 8080 
            initialDelaySeconds: 10 
            periodSeconds: 10 
          livenessProbe:
            httpGet: 
              path: /
              port: 8080 
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
