apiVersion: v1
kind: ConfigMap 
metadata:
  name: prometheus-config 
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes'
        static_configs:
          - target: ['localhost:9090']
